### ISSUE TITLE
强制踢下线问题

### ISSUE THREAD

**Issue by LockeyWu** [easemob/chat-android#22]
关于kickAllDevices  方法使用
报错
    java.lang.UnsatisfiedLinkError: No implementation found for void com.hyphenate.chat.adapter.EMAError.nativeInit() (tried Java_com_hyphenate_chat_adapter_EMAError_nativeInit and Java_com_hyphenate_chat_adapter_EMAError_nativeInit__)

**Comment by LockeyWu** [comment]
就是使用这个方法  可以将指定账号username, password 强制下线 好像 ios 的sdk可以

**Comment by jinanzhuan** [comment]
> 就是使用这个方法 可以将指定账号username, password 强制下线 好像 ios 的sdk可以

这个需要先初始化SDK，否则一些.so库还没有加载，再调用到相关的方法的话，就会报错。
