### ISSUE TITLE
编译失败：Task :app:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by ZhaoYidong** [easemob/chat-android#53]
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.ExceptionInInitializerError

请问是什么愿意呢？

**Comment by ZhaoYidong** [comment]
修改了room的版本号后，目前问题是：
Execution failed for task ':app:processDebugManifest'.
> Could not get unknown property 'manifestOutputDirectory' for task ':app:processDebugManifest' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.

**Comment by jinanzhuan** [comment]
> 修改了room的版本号后，目前问题是： Execution failed for task ':app:processDebugManifest'.
> 
> > Could not get unknown property 'manifestOutputDirectory' for task ':app:processDebugManifest' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.

您是否使用的是Mac m1？如果是的话，可以考虑将room升级到2.4.0-alpha04版本以后

**Comment by jinanzhuan** [comment]
> 修改了room的版本号后，目前问题是： Execution failed for task ':app:processDebugManifest'.
> 
> > Could not get unknown property 'manifestOutputDirectory' for task ':app:processDebugManifest' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.

请试用最新的 master 分支，看是否还有上述的问题，如果还有编译方面的问题，欢迎您继续提出。
