### ISSUE TITLE
找不到类文件

### ISSUE THREAD

**Issue by jiangjunzailushang** [easemob/chat-android#58]
发送/接收图片消息时用到类:com.hyphenate.easeui.utils.EaseFileUtils中有引用com.hyphenate.util.EMFileHelper。但是没有找到对应的包和类。同样的还有com.hyphenate.util.EMLog也找不到。
`public static boolean isFileExistByUri(Context context, Uri fileUri) {
        return EMFileHelper.getInstance().isFileExist(fileUri);
    }`

**Comment by jinanzhuan** [comment]
> 发送/接收图片消息时用到类:com.hyphenate.easeui.utils.EaseFileUtils中有引用com.hyphenate.util.EMFileHelper。但是没有找到对应的包和类。同样的还有com.hyphenate.util.EMLog也找不到。 `public static boolean isFileExistByUri(Context context, Uri fileUri) { return EMFileHelper.getInstance().isFileExist(fileUri); }`

从您的描述看，是UIKit库和SDK库都没有从远程仓库pull下来。
