### ISSUE TITLE
手机网络登不上 wifi能登上  有这个问题？？

### ISSUE THREAD

**Issue by naojiangzhalie666** [easemob/chat-android#62]
手机网络登不上 wifi能登上  有这个问题？？

**Comment by jinanzhuan** [comment]
> 手机网络登不上 wifi能登上 有这个问题？？

您好，请提供一下对应的日志，我找研发人员看下。

**Comment by jinanzhuan** [comment]
> 手机网络登不上 wifi能登上 有这个问题？？

正常情况是不分手机网络环境和 WIFI 环境的。请问目前是否还有问题，如果有问题的话，可以通过如下方式获取一下当时的日志：
adb pull /sdcard/android/data/{应用包名}/{App Key}/core_log/easemob.log
或者通过手机的文件管理，通过对应的路径找到对应的日志文件，发给我们，我们需要通过日志分析一下原因。
