### ISSUE TITLE
sendHonorPushTokenToServer

### ISSUE THREAD

**Issue by LiuYimin** [easemob/chat-android#91]
dev分支,编译报这个错

**Comment by jinanzhuan** [comment]
> dev分支,编译报这个错

感谢您的反馈！dev分支是我们的开发分支，依赖的是本地的SDK库，会出现编译不通过的情况。您想使用这个工程的话，请你使用 master 分支。我们开发完成，测试完成，以及 SDK 发布以后，会及时将 dev 分支合并到 master 分支。再次对您的使用和支持表示感谢！
